apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodeployment
spec:
  selector: 
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-web-app
          image: subodhsohoni/newimg:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: demo-app
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
  selector:
    app: demo-app
  type: LoadBalancer